app/src/main/java/cc/cc1234/app/controller/NodeViewController.java

feat: add alert dialog on delete node #21

---

domain/src/main/resources/log4j2.xml

feat: log config update #42

---

app/src/main/java/cc/cc1234/app/controller/NodeInfoViewController.java
app/src/main/java/cc/cc1234/app/controller/NodeViewController.java
app/src/main/java/cc/cc1234/app/controller/ServerViewController.java
app/src/main/java/cc/cc1234/app/listener/DefaultTreeNodeListener.java
app/src/main/resources/assets/style.css
app/src/main/resources/fxml/NodeInfoView.fxml

1. fix incorrect num of child
2. support ctime/mtime format
3. redeisgn node info layout

node info redesign

---

app/src/main/java/cc/cc1234/app/controller/NodeInfoViewController.java
app/src/main/resources/assets/style.css
app/src/main/resources/fxml/NodeInfoView.fxml
infrastructure/src/main/java/cc/cc1234/client/curator/CuratorTreeCacheListener.java
spi/src/main/java/cc/cc1234/spi/node/ZkNode.java

feat:support node data charset switch

---

infrastructure/src/main/java/cc/cc1234/util/JsonUtils.java

fix: create config file error when init

---

app/src/main/java/cc/cc1234/app/controller/NodeViewController.java
domain/src/main/java/cc/cc1234/domain/zookeeper/service/ZookeeperDomainService.java

feat: add check before execute 4-letter-command

---

app/build.gradle
app/src/main/java/cc/cc1234/app/controller/ServerViewController.java
app/src/main/java/cc/cc1234/app/facade/PrettyZooFacade.java
app/src/main/java/cc/cc1234/app/listener/DefaultConfigurationListener.java
app/src/main/java/cc/cc1234/app/view/cell/ZkServerListCell.java
app/src/main/java/cc/cc1234/app/vo/ConfigurationVOTransfer.java
app/src/main/java/cc/cc1234/app/vo/ServerConfigurationVO.java
app/src/main/resources/fxml/ServerView.fxml
domain/src/main/java/cc/cc1234/domain/configuration/entity/Configuration.java
domain/src/main/java/cc/cc1234/domain/configuration/entity/ServerConfiguration.java
domain/src/main/java/cc/cc1234/domain/configuration/factory/ConfigurationFactory.java
infrastructure/src/main/java/cc/cc1234/config/JsonPrettyZooConfigRepository.java
spi/src/main/java/cc/cc1234/spi/config/PrettyZooConfigRepository.java
spi/src/main/java/cc/cc1234/spi/config/model/ServerConfigData.java

feat: support alias & add vm option

---

app/src/main/java/cc/cc1234/PrettyZooApplication.java
app/src/main/java/cc/cc1234/app/controller/MainViewController.java
app/src/main/java/cc/cc1234/app/util/ShortcutKeys.java

feat: support shortcut key for new

---

app/src/main/java/cc/cc1234/app/controller/MainViewController.java
app/src/main/java/cc/cc1234/app/controller/ServerViewController.java

feat: support double click to connect zookeepr

---

app/src/main/java/cc/cc1234/app/controller/MainViewController.java
app/src/main/java/cc/cc1234/app/facade/PrettyZooFacade.java
app/src/main/resources/assets/style.css
app/src/main/resources/fxml/MainView.fxml
app/src/main/resources/fxml/NodeInfoView.fxml
app/src/main/resources/fxml/ServerView.fxml
core/src/main/java/cc/cc1234/core/configuration/entity/Configuration.java
core/src/main/java/cc/cc1234/core/configuration/factory/ConfigurationFactory.java
core/src/main/java/cc/cc1234/core/configuration/service/ConfigurationDomainService.java
specification/src/main/java/cc/cc1234/specification/config/model/ConfigData.java

Support change global font-size

---

app/src/main/java/cc/cc1234/app/listener/DefaultConfigurationListener.java
app/src/main/java/cc/cc1234/app/view/cell/ZkServerListCell.java

fix(#123): lost connected status when create new server

---

app/src/main/java/cc/cc1234/app/controller/NodeInfoViewController.java
app/src/main/resources/assets/style.css
app/src/main/resources/fxml/NodeInfoView.fxml

Support node data area zoom in or out

---

app/src/main/java/cc/cc1234/app/controller/NodeInfoViewController.java
app/src/main/java/cc/cc1234/app/facade/PrettyZooFacade.java
app/src/main/java/module-info.java
core/src/main/java/cc/cc1234/core/zookeeper/entity/Zookeeper.java
core/src/main/java/cc/cc1234/core/zookeeper/service/ZookeeperDomainService.java
specification-impl/src/main/java/cc/cc1234/client/curator/CuratorZookeeperConnection.java
specification/src/main/java/cc/cc1234/specification/connection/ZookeeperConnection.java

fix: metadata not refresh after data update

---

app/src/main/java/cc/cc1234/app/controller/ServerViewController.java
app/src/main/java/cc/cc1234/app/view/cell/ZkServerListCell.java
app/src/main/java/cc/cc1234/app/vo/ConfigurationVOTransfer.java
app/src/main/java/cc/cc1234/app/vo/ServerConfigurationVO.java
app/src/main/java/cc/cc1234/app/vo/ServerStatus.java
app/src/main/java/cc/cc1234/version/Version.java
build.gradle
specification-impl/src/main/java/cc/cc1234/client/curator/CuratorZookeeperConnectionFactory.java
specification/src/main/java/cc/cc1234/specification/listener/ServerListener.java

feat: support reconnect automatic

---

app/src/main/java/cc/cc1234/app/controller/NodeViewController.java
app/src/main/java/cc/cc1234/app/facade/PrettyZooFacade.java
app/src/main/java/cc/cc1234/app/view/cell/ZkNodeTreeCell.java
app/src/main/resources/fxml/NodeListView.fxml
app/src/main/resources/i18n_en.properties
app/src/main/resources/i18n_zh_cn.properties
core/src/main/java/cc/cc1234/core/zookeeper/entity/Zookeeper.java
core/src/main/java/cc/cc1234/core/zookeeper/service/ZookeeperDomainService.java
specification-impl/src/main/java/cc/cc1234/client/curator/CuratorZookeeperConnection.java
specification/src/main/java/cc/cc1234/specification/connection/ZookeeperConnection.java

feat: support node multiple selection

---

app/build.gradle
app/src/main/resources/i18n_zh_CN.properties

fix: can't relaunch application after switch language

---

app/src/main/java/cc/cc1234/app/controller/MainViewController.java
app/src/main/java/cc/cc1234/app/controller/NodeInfoViewController.java
app/src/main/java/cc/cc1234/app/controller/NodeViewController.java
app/src/main/java/cc/cc1234/app/util/FXMLs.java
app/src/main/java/cc/cc1234/app/util/ResourceBundleUtils.java
app/src/main/java/cc/cc1234/app/view/cell/ZkNodeTreeCell.java
app/src/main/java/cc/cc1234/app/view/cell/ZkServerListCell.java
app/src/main/resources/cc/cc1234/i18n/lang_en.properties
app/src/main/resources/cc/cc1234/i18n/lang_zh_CN.properties

feat: add node data conflict check when refresh it

---

app/src/main/java/cc/cc1234/app/controller/MainViewController.java
app/src/main/java/cc/cc1234/app/controller/NodeViewController.java
app/src/main/java/cc/cc1234/app/controller/ServerViewController.java
app/src/main/java/cc/cc1234/app/facade/PrettyZooFacade.java
app/src/main/java/cc/cc1234/app/listener/DefaultConfigurationListener.java
app/src/main/java/cc/cc1234/app/validator/StringNotBlankValidator.java
app/src/main/java/cc/cc1234/app/validator/ZkPortValidator.java
app/src/main/java/cc/cc1234/app/view/cell/ZkServerListCell.java
app/src/main/java/cc/cc1234/app/vo/ConfigurationVOTransfer.java
app/src/main/java/cc/cc1234/app/vo/ServerConfigurationVO.java
app/src/main/resources/fxml/ServerView.fxml
core/src/main/java/cc/cc1234/core/configuration/entity/Configuration.java
core/src/main/java/cc/cc1234/core/configuration/entity/ServerConfiguration.java
core/src/main/java/cc/cc1234/core/configuration/factory/ConfigurationFactory.java
core/src/main/java/cc/cc1234/core/configuration/service/ConfigurationDomainService.java
core/src/main/java/cc/cc1234/core/zookeeper/entity/SSHTunnel.java
core/src/main/java/cc/cc1234/core/zookeeper/entity/Zookeeper.java
core/src/main/java/cc/cc1234/core/zookeeper/factory/ZookeeperFactory.java
core/src/main/java/cc/cc1234/core/zookeeper/service/ZookeeperDomainService.java
specification-impl/src/main/java/cc/cc1234/client/curator/CuratorZookeeperConnectionFactory.java
specification-impl/src/main/java/cc/cc1234/config/JsonPrettyZooConfigRepository.java
specification/src/main/java/cc/cc1234/specification/config/model/ConfigData.java
specification/src/main/java/cc/cc1234/specification/config/model/ServerConfigData.java
specification/src/main/java/cc/cc1234/specification/connection/ZookeeperParams.java

feat: split host textfield into host and port

---

core/src/main/java/cc/cc1234/core/zookeeper/entity/SSHTunnel.java
core/src/main/java/cc/cc1234/core/zookeeper/entity/Zookeeper.java

fix: can't connect with ssh-tunnel

---

app/src/main/java/cc/cc1234/app/controller/ServerViewController.java
app/src/main/java/cc/cc1234/app/facade/PrettyZooFacade.java
app/src/main/java/cc/cc1234/app/listener/DefaultConfigurationListener.java
app/src/main/java/cc/cc1234/app/validator/PortValidator.java
app/src/main/java/cc/cc1234/app/vo/ConfigurationVOTransfer.java
app/src/main/java/cc/cc1234/app/vo/ServerConfigurationVO.java
app/src/main/resources/fxml/ServerView.fxml

feat: split ssh-tunnel remote server input field

---

.github/workflows/jpackage.yml
app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

1. upgrade gradle to 7.0
2. upgrade java version to 17
3. upgrade jlink plugin to 2.24.4

feat: upgrade java version to 17

---

app/src/main/java/cc/cc1234/app/controller/NodeViewController.java

feat: show node info when select search result

---

app/src/main/java/cc/cc1234/app/controller/NodeInfoViewController.java

fix: json highlight not work in windows when click twice JSON button

---

app/src/main/resources/assets/css/dark/style.css
app/src/main/resources/assets/css/default/style.css

feat: node tree ui optimize

---

app/src/main/java/cc/cc1234/app/controller/MainViewController.java
app/src/main/java/cc/cc1234/version/VersionChecker.java

fix: ignore toast if check failed when app start
